log_level: "debug"
listen: ":8080"
cert: "test/server.crt"
key: "test/server.key"
cf_api: "https://api.cf.sap.hana.ondemand.com"
pcap_server_port: "9494"
pcap_server_client_cert: "test/client.crt"
pcap_server_client_key: "test/client.key"
pcap_server_ca_cert: "test/cacert.pem"

