---
name: pcap-server

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm

instance_groups:
  - name: pcap-server-api
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks: [{name: default}]
    jobs:
      - name: pcap-server-api
        release: pcap-server
        properties:
          pcap-server-api:
            enable_server_tls: false
            client_skip_verify: true
            cf_api: ((cf-api))
            client_cert: ((pcap_server_api_mtls.certificate))
            client_key: ((pcap_server_api_mtls.private_key))
            ca_cert: ((pcap_server_api_mtls.ca))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-bionic
    version: latest

releases:
  - name: bpm
    version: 1.1.8
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
    sha1: c956394fce7e74f741e4ae8c256b480904ad5942
  - name: pcap-server
    version: 0+dev.1
    url: https://github.com/domdom82/pcap-server-release/releases/download/v0.0.1/pcap-server-0.0.1.tgz
    sha1: a1655c1992b911fef3ad0b46c5abb8a0217ef0a2
  - name: bosh-dns-aliases
    version: 0.0.4
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.4
    sha1: 55b3dced813ff9ed92a05cda02156e4b5604b273
  - name: routing
    version: 0.232.0
    url: https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.232.0
    sha1: 1150a7c89a04db07145c906ccdbfda7424e6dfc6

variables:
  - name: pcap_server_api_mtls
    type: certificate
    update_mode: converge
    options:
      ca: pcap_server_ca
      common_name: pcap_server_api_mtls
      alternative_names:
        - pcap-server-api.service.cf.internal
      extended_key_usage:
        - client_auth
        - server_auth