---
name: pcap-server

addons:
  - name: bpm
    jobs:
      - name: bpm
        release: bpm
  - name: bosh-dns-aliases
    jobs:
      - name: bosh-dns-aliases
        release: bosh-dns-aliases
        properties:
          aliases:
            - domain: nats.service.cf.internal
              targets:
                - deployment: cf
                  domain: bosh
                  instance_group: nats
                  network: cf
                  query: '*'
            - domain: _.nats.service.cf.internal
              targets:
                - deployment: cf
                  domain: bosh
                  instance_group: nats
                  network: cf
                  query: _
instance_groups:
  - name: pcap-server-api
    azs:
      - z1
    instances: 2
    vm_type: ((pcap_server_api.vm_type))
    stemcell: default
    networks: ((pcap_server_api.networks))
    jobs:
      - name: pcap-server-api
        release: pcap-server
        properties:
          pcap-server-api:
            enable_server_tls: false
            client_skip_verify: true
            cf_api: ((pcap_server_api.cf_api))
            client_cert: ((pcap_server_api_mtls.certificate))
            client_key: ((pcap_server_api_mtls.private_key))
            ca_cert: ((pcap_server_api_mtls.ca))
      - name: route_registrar
        release: routing
        consumes:
          nats-tls:
            from: nats-tls
            deployment: cf
        properties:
          route_registrar:
            routes:
              - name: pcap-server-public-endpoint
                registration_interval: 20s
                port: 8080
                uris:
                  - ((route_registrar.public_route))
            port: 8080
          nats:
            tls:
              enabled: true
              client_cert: ((nats.client_cert))
              client_key: ((nats.client_key))

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-bionic
    version: latest

releases:
  - name: bpm
    version: 1.1.8
    url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.8
    sha1: c956394fce7e74f741e4ae8c256b480904ad5942
  - name: pcap-server
    version: 0+dev.4
    url: https://github.com/domdom82/pcap-server-release/releases/download/v0.0.1/pcap-server-0.0.1.tgz
    sha1: a1655c1992b911fef3ad0b46c5abb8a0217ef0a2
  - name: bosh-dns-aliases
    version: 0.0.4
    url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-aliases-release?v=0.0.4
    sha1: 55b3dced813ff9ed92a05cda02156e4b5604b273
  - name: routing
    version: 0.232.0
    url: https://bosh.io/d/github.com/cloudfoundry/routing-release?v=0.232.0
    sha1: 1150a7c89a04db07145c906ccdbfda7424e6dfc6

variables:
  - name: pcap_server_api_mtls
    type: certificate
    update_mode: converge
    options:
      ca: ((pcap_server_api.ca_path))
      common_name: pcap_server_api_mtls
      alternative_names:
        - pcap-server-api.service.cf.internal
      extended_key_usage:
        - client_auth
        - server_auth
